EthoTrak/Controllers/AnimalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.DatabaseModels;

namespace EthoTrak.Controllers
{
    public class AnimalController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Add()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var species = session.QueryOver<TblSPEC_ID>().List();

                    IEnumerable<SelectListItem> list = species.Select(s => new SelectListItem
                    {
                        Value = s.SPEC_ID.ToString(),
                        Text = s.SPEC_NAME
                    });

                    ViewBag.species = list;
                }
            }
            var animal = new TblANIM_ID();
            return View(animal);
        }

        [HttpPost]
        public ActionResult Add(TblANIM_ID animal)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    animal.ACT_DT = System.DateTime.Now;

                    if (ModelState.IsValid)
                    {
                        session.Save(animal);
                        transaction.Commit();
                    }
                    else
                    {                        
                        var species = session.QueryOver<TblSPEC_ID>().List();

                        IEnumerable<SelectListItem> list = species.Select(s => new SelectListItem
                        {
                            Value = s.SPEC_ID.ToString(),
                            Text = s.SPEC_NAME
                        });

                        ViewBag.species = list;
                        return View(animal);
                    }
                }
            }

            return Redirect("/Animal/All");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var animal = session.QueryOver<TblANIM_ID>().Where(x => x.ANIM_ID == id).SingleOrDefault();

                    if (animal == null)
                    {
                        return HttpNotFound();
                    }

                    var species = session.QueryOver<TblSPEC_ID>().List();

                    IEnumerable<SelectListItem> list = species.Select(s => new SelectListItem
                    {
                        Value = s.SPEC_ID.ToString(),
                        Text = s.SPEC_NAME
                    });

                    ViewBag.species = list;

                    return View(animal);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, TblANIM_ID animal)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbAnimal = session.QueryOver<TblANIM_ID>().Where(x => x.ANIM_ID == id).SingleOrDefault();

                    dbAnimal.DESC_ANIM = animal.DESC_ANIM;
                    dbAnimal.SPEC_ID = animal.SPEC_ID;
                    dbAnimal.INST_ID = animal.INST_ID;
                    dbAnimal.SEX = animal.SEX;
                    dbAnimal.STATUS = animal.STATUS;
                    dbAnimal.COMMENTS = animal.COMMENTS;
                    dbAnimal.ACT_DT = System.DateTime.Now;

                    session.Save(dbAnimal);

                    transaction.Commit();
                }
            }
            return Redirect("/Animal/All");
        }

        public ActionResult All()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.animals = session.QueryOver<TblANIM_ID>().List().OrderBy(x => x.ANIM_ID);
                }
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbAnimal = session.QueryOver<TblANIM_ID>().Where(x => x.ANIM_ID == id).SingleOrDefault();
                    session.Delete(dbAnimal);
                    transaction.Commit();
                }
            }
            return Redirect("/Animal/All");
        }
    }
}

EthoTrak/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.DatabaseModels;

namespace EthoTrak.Controllers
{
    public class AreaController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Add()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var exhibits = session.QueryOver<TblEXHIB_ID>().List();

                    IEnumerable<SelectListItem> list = exhibits.Select(exhibit => new SelectListItem
                    {
                        Value = exhibit.EXHIB_ID.ToString(),
                        Text = exhibit.EXHIB
                    });

                    ViewBag.exhibits = list;
                }
            }

            var area = new TblAREA_ID();
            return View(area);
        }

        [HttpPost]
        public ActionResult Add(TblAREA_ID a)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    a.ACT_DT = System.DateTime.Now;

                    session.Save(a);

                    transaction.Commit();
                }
            }

            return Redirect("/Area/All");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var area = session.QueryOver<TblAREA_ID>().Where(x => x.AREA_ID == id).SingleOrDefault();

                    if (area == null)
                    {
                        return HttpNotFound();
                    }

                    var exhibits = session.QueryOver<TblEXHIB_ID>().List();

                    IEnumerable<SelectListItem> list = exhibits.Select(exhibit => new SelectListItem
                    {
                        Value = exhibit.EXHIB_ID.ToString(),
                        Text = exhibit.EXHIB
                    });

                    ViewBag.exhibits = list;

                    return View(area);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, TblAREA_ID a)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbArea = session.QueryOver<TblAREA_ID>().Where(x => x.AREA_ID == id).SingleOrDefault();

                    dbArea.AREA = a.AREA;
                    dbArea.EXHIB_ID = a.EXHIB_ID;
                    dbArea.ACT_DT = System.DateTime.Now;

                    session.Save(dbArea);

                    transaction.Commit();
                }
            }
            return Redirect("/Area/All");
        }

        public ActionResult All()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.areas = session.QueryOver<TblAREA_ID>().List().OrderBy(x => x.AREA_ID);
                }
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbEnclosures = session.QueryOver<TblENCLOS_ID>().Where(x => x.AREA_ID == id).List();

                    foreach (var enclosure in dbEnclosures)
                    {
                        EthoTrak.Controllers.EnclosureController ec = new EnclosureController();
                        ec.Delete(enclosure.ENCLOS_ID);
                    }
                    
                    var dbArea = session.QueryOver<TblAREA_ID>().Where(x => x.AREA_ID == id).SingleOrDefault();
                    session.Delete(dbArea);
                    transaction.Commit();
                }
            }
            return Redirect("/Area/All");
        }
    }
}

EthoTrak/Controllers/ExhibitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.DatabaseModels;

namespace EthoTrak.Controllers
{
    public class ExhibitController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Add()
        {
            var exhibit = new TblEXHIB_ID();
            return View(exhibit);
        }

        [HttpPost]
        public ActionResult Add(TblEXHIB_ID exhibit)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    exhibit.ADD_DATE = System.DateTime.Now;
                    exhibit.ACT_DT = exhibit.ADD_DATE;

                    session.Save(exhibit);

                    transaction.Commit();
                }
            }

            return Redirect("/Exhibit/All");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var exhibit = session.QueryOver<TblEXHIB_ID>().Where(x => x.EXHIB_ID == id).SingleOrDefault();

                    if (exhibit == null)
                    {
                        return HttpNotFound();
                    }

                    return View(exhibit);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, TblEXHIB_ID exhibit)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbExhibit = session.QueryOver<TblEXHIB_ID>().Where(x => x.EXHIB_ID == id).SingleOrDefault();

                    dbExhibit.EXHIB = exhibit.EXHIB;
                    dbExhibit.ACT_DT = System.DateTime.Now;
                    
                    session.Save(dbExhibit);

                    transaction.Commit();
                }
            }
            return Redirect("/Exhibit/All");
        }

        public ActionResult All()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.exhibits = session.QueryOver<TblEXHIB_ID>().List().OrderBy(x => x.EXHIB_ID);
                }
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbAreas = session.QueryOver<TblAREA_ID>().Where(x => x.EXHIB_ID == id).List();

                    foreach (var area in dbAreas) 
                    {
                        EthoTrak.Controllers.AreaController ac = new AreaController();
                        ac.Delete(area.AREA_ID);
                    }

                    var dbExhibit = session.QueryOver<TblEXHIB_ID>().Where(x => x.EXHIB_ID == id).SingleOrDefault();
                    session.Delete(dbExhibit);
                    transaction.Commit();
                }
            }
            return Redirect("/Exhibit/All");
        }
    }
}

EthoTrak/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.Models;

namespace EthoTrak.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "This is the index.";
            
            return View();
        }

        public ActionResult Management()
        {
            return View();
        }
    }
}

EthoTrak/Controllers/KeeperController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.DatabaseModels;

namespace EthoTrak.Controllers
{
    public class KeeperController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Add()
        {
            var keeper = new TblKEEP_ID();
            return View(keeper);
        }

        [HttpPost]
        public ActionResult Add(TblKEEP_ID keeper)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    keeper.ACT_DT = System.DateTime.Now;
                    keeper.ADD_DATE = keeper.ACT_DT;

                    session.Save(keeper);
                    transaction.Commit();
                }
            }
            return Redirect("/Keeper/All");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var keeper = session.QueryOver<TblKEEP_ID>().Where(x => x.KEEP_ID == id).SingleOrDefault();

                    if (keeper == null)
                    {
                        return HttpNotFound();
                    }

                    ViewBag.Date = keeper.ADD_DATE.Value.ToShortDateString();

                    return View(keeper);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, TblKEEP_ID keeper)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbKeeper = session.QueryOver<TblKEEP_ID>().Where(x => x.KEEP_ID == id).SingleOrDefault();

                    dbKeeper.FIRST = keeper.FIRST;
                    dbKeeper.MID_INIT = keeper.MID_INIT;
                    dbKeeper.LAST = keeper.LAST;
                    dbKeeper.ADD_DATE = keeper.ADD_DATE;
                    dbKeeper.ACT_DT = System.DateTime.Now;

                    session.Save(dbKeeper);

                    transaction.Commit();
                }
            }
            return Redirect("/Keeper/All");
        }

        public ActionResult All()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.keepers = session.QueryOver<TblKEEP_ID>().List().OrderBy(x => x.KEEP_ID);
                }
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbKeeper = session.QueryOver<TblKEEP_ID>().Where(x => x.KEEP_ID == id).SingleOrDefault();
                    session.Delete(dbKeeper);
                    transaction.Commit();
                }
            }
            return Redirect("/Keeper/All");
        }
    }
}

EthoTrak/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

EthoTrak/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

EthoTrak/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<center><h3>Welcome to EthoTrak.org</h3></center>
<br />


<p style="font-size:15px; line-height:25px;">In 2003, Brookfield Zoo began a long-term effort to develop an easy-to-use, flexible, digital system for
collecting basic behavioral data within zoological institutions, a system that we termed EthoTrak.</p>
<br />
<p style="font-size:15px; line-height:25px;">The software is particularly notable in that it is designed specifically for multiinstitutional
use as it compiles data from across participating institutions into a single functional database. To
achieve this goal, participating institutions must use standardized behavioral terminology (established ethograms)
in order to maintain consistency across institutions in how behaviors are named, categorized, and quantified.
Only with uniform behavioral data collection methods can information from multiple participants be analyzed,
compared and shared.</p>
<br />
<p style="font-size:15px; line-height:25px;">With EthoTrak, the time-intensive efforts typically required to collect and enter data are eliminated since
paper is not required to collect and analyze data. The time commitment for use is modest with the data collection
protocol easily integrating into any time-challenged schedule.</p>

EthoTrak/Views/Home/Management.cshtml
@{
    ViewBag.Title = "Management";
}

<table class="table">
    <tr>
        <td style="border-top: 0px; width: 33%;">
            <center>
                @if (User.IsInRole("Administrator")) 
                {
                @Html.ActionLink("Manage Species", "AllAdmin", "Species", null, new { @class = "btn btn-large btn-info btn-block" })
                }
                else
                {
                @Html.ActionLink("View Species", "All", "Species", null, new { @class = "btn btn-large btn-block" })
                }
                <br />
        @Html.ActionLink("Manage Animals", "All", "Animal", null, new { @class = "btn btn-large btn-block" })<br />
        @Html.ActionLink("Move Animals", "PickExhibit", "EnclosureAssignment", null, new { @class = "btn btn-large btn-block" })<br />
    @Html.ActionLink("View Enclosure Configurations", "All", "EnclosureAssignment", null, new { @class = "btn btn-large btn-block" })<br />
                    @if (User.IsInRole("Administrator")) 
                {
                @Html.ActionLink("Manage Behaviors", "All", "Behavior", null, new { @class = "btn btn-large btn-info btn-block" })
                }
        </center>
        </td>
        <td style="border-top: 0px; width: 33%;">
            <center>
        @Html.ActionLink("Manage Exhibits", "All", "Exhibit", null, new { @class = "btn btn-large btn-block" })<br />
        @Html.ActionLink("Manage Areas", "All", "Area", null, new { @class = "btn btn-large btn-block" })<br />
        @Html.ActionLink("Manage Enclosures", "All", "Enclosure", null, new { @class = "btn btn-large btn-block" })<br />
        @Html.ActionLink("Manage Locations", "All", "Location", null, new { @class = "btn btn-large btn-block" })<br />
    </center>
        </td>
        <td style="border-top: 0px; width: 33%;">
            <center>
        @Html.ActionLink("Manage Keepers", "All", "Keeper", null, new { @class = "btn btn-large btn-block" })<br />
        @Html.ActionLink("Assign Keepers to Exhibits", "PickExhibit", "KeeperAssignment", null, new { @class = "btn btn-large btn-block" })<br />
        @Html.ActionLink("View Keeper Assignments", "All", "KeeperAssignment", null, new { @class = "btn btn-large btn-block" })
    </center>
        </td>
</table>