EthoTrak/Controllers/SpeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.DatabaseModels;

namespace EthoTrak.Controllers
{
    
    public class SpeciesController : Controller
    {
        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Add()
        {
            var species = new TblSPEC_ID();
            return View(species);
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Add(TblSPEC_ID species)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    species.ACT_DT = System.DateTime.Now;

                    session.Save(species);
                    transaction.Commit();                    
                }
            }
            return Redirect("/Species/AllAdmin");
        }

        [HttpGet]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var species = session.QueryOver<TblSPEC_ID>().Where(x => x.SPEC_ID == id).SingleOrDefault();

                    if (species == null)
                    {
                        return HttpNotFound();
                    }

                    return View(species);
                }
            }
        }

        [HttpPost]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id, TblSPEC_ID species)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbSpecies = session.QueryOver<TblSPEC_ID>().Where(x => x.SPEC_ID == id).SingleOrDefault();

                    dbSpecies.SPEC_NAME = species.SPEC_NAME;
                    dbSpecies.LATIN_NAME = species.LATIN_NAME;
                    dbSpecies.COMMENTS = species.COMMENTS;
                    dbSpecies.ACT_DT = System.DateTime.Now;

                    session.Save(dbSpecies);

                    transaction.Commit();
                }
            }
            return Redirect("/Species/AllAdmin");
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult AllAdmin()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.species = session.QueryOver<TblSPEC_ID>().List().OrderBy(x => x.SPEC_ID);
                }
            }

            return View();
        }

        [Authorize(Roles = "Free, Paid Low, Paid High, Administrator")]
        public ActionResult All()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.species = session.QueryOver<TblSPEC_ID>().List().OrderBy(x => x.SPEC_ID);
                }
            }

            return View();
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbSpecies = session.QueryOver<TblSPEC_ID>().Where(x => x.SPEC_ID == id).SingleOrDefault();
                    session.Delete(dbSpecies);
                    transaction.Commit();
                }
            }
            return Redirect("/Species/AllAdmin");
        }
    }
}

EthoTrak/Views/Species/Add.cshtml
@model EthoTrak.DatabaseModels.TblSPEC_ID

@section JavaScript
{
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")

    <script>
        $(document).ready(function () { $("#Date").datepicker(); });
    </script>
}

@{
    ViewBag.Title = "Species - Add";
}

<br />
<center>@Html.ActionLink("Go back", "AllAdmin", "Species", null, new { @class="btn"})</center>
<br />

@using (Html.BeginForm())
{
    <fieldset>

        <legend>Add a Species</legend>

        <div class="editor-label">
            Name
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.SPEC_NAME)
        </div>

        <div class="editor-label">
            Latin Name
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.LATIN_NAME)
        </div>

        <div class="editor-label">
            Comments
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.COMMENTS, new { style = "height:100px;" } )
        </div>

        <br />
        <center><input type="submit" class="btn btn-success" value="Add Species" /></center>
        <br />

    </fieldset>
}

EthoTrak/Views/Species/All.cshtml
@using EthoTrak.DatabaseModels

@section JavaScript
{
   <script type="text/javascript" src="@Url.Content("/Scripts/custom.js")"></script>
}

@{
    ViewBag.Title = "Species";
}
<h3>Species :</h3>
<center>
    @Html.ActionLink("Go back", "Management", "Home", null, new { @class="btn"})
</center>
<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Latin Name</th>
        <th>Comments</th>
        <th>Last Modified</th>
    </tr>

    @foreach (TblSPEC_ID species in @ViewBag.species)
    {

        <tr>
            <td>@species.SPEC_ID</td>
            <td>@species.SPEC_NAME</td>
            <td>@species.LATIN_NAME</td>
            <td>@species.COMMENTS</td>
            <td>@species.ACT_DT</td>
        </tr>
    }
</table>

EthoTrak/Views/Species/AllAdmin.cshtml
@using EthoTrak.DatabaseModels

@section JavaScript
{
   <script type="text/javascript" src="@Url.Content("/Scripts/custom.js")"></script>
}

@{
    ViewBag.Title = "Species";
}
<h3>Species :</h3>
<center>
    <span style="padding-right:20px;">
    @Html.ActionLink("Go back", "Management", "Home", null, new { @class="btn"})
    </span>
    @Html.ActionLink("Add a species", "Add", "Species", null, new { @class="btn"})
</center>
<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Latin Name</th>
        <th>Comments</th>
        <th>Last Modified</th>
        <th></th>
        <th></th>
    </tr>

    @foreach (TblSPEC_ID species in @ViewBag.species)
    {

        <tr>
            <td>@species.SPEC_ID</td>
            <td>@species.SPEC_NAME</td>
            <td>@species.LATIN_NAME</td>
            <td>@species.COMMENTS</td>
            <td>@species.ACT_DT</td>
            <td>@Html.ActionLink("Edit", "Edit", "Species", new { id = species.SPEC_ID }, new { @class="btn btn-small"})</td>
            <td>@Html.ActionLink("Delete", "Delete", "Species", new { id = species.SPEC_ID }, new { @class="btn btn-small btn-danger", onclick = " return DeleteConfirm('species')" })</td>
        </tr>
    }
</table>

EthoTrak/Views/Species/Edit.cshtml
@model EthoTrak.DatabaseModels.TblSPEC_ID

@{
    ViewBag.Title = "Species - Edit";
}

<br />
<center>@Html.ActionLink("Go back", "AllAdmin", "Species", null, new { @class="btn"})</center>
<br />

@using (Html.BeginForm())
{
    <fieldset>
        
        <div class="editor-label">
            Name
        </div>
            <div class="editor-field">
            @Html.TextBoxFor(model => model.SPEC_NAME)
        </div>

        <div class="editor-label">
            Latin Name
        </div>
            <div class="editor-field">
            @Html.TextBoxFor(model => model.LATIN_NAME)
        </div>
      
        <div class="editor-label">
            Comments
        </div>
            <div class="editor-field">
            @Html.TextAreaFor(model => model.COMMENTS, new { style = "height:100px;" } )
        </div>    

         <br />
        <center><input type="submit" class="btn btn-success" value="Save Changes" /></center>
        <br />

    </fieldset>
}

EthoTrak/Views/Species/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Species</h2>

@Html.ActionLink("Add a Species", "Add", "Species")
<br />
@Html.ActionLink("List all Species", "All", "Species")