EthoTrak/Controllers/KeeperAssignmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.DatabaseModels;

namespace EthoTrak.Controllers
{
    public class KeeperAssignmentController : Controller
    {

        public ActionResult PickExhibit()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var exhibits = session.QueryOver<TblEXHIB_ID>().List();

                    IEnumerable<SelectListItem> list = exhibits.Select(exhibit => new SelectListItem
                    {
                        Value = exhibit.EXHIB_ID.ToString(),
                        Text = exhibit.EXHIB
                    });

                    ViewBag.exhibits = list;
                }
            }
            return View();
        }

        public ActionResult ShowKeepers(int idExhibit)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var keepersAlreadyAssigned = session.QueryOver<TblEXHIB_KEEP>().Where(x => x.EXHIB_ID == idExhibit).Select(x => x.KEEP_ID).List<int>().ToArray();

                    var keepersNotAssigned = session.QueryOver<TblKEEP_ID>().WhereRestrictionOn(x => x.KEEP_ID).Not.IsIn(keepersAlreadyAssigned).Select(x => x.KEEP_ID).List<int>();

                    List<TblKEEP_ID> keepers = new List<TblKEEP_ID>();

                    foreach (var keeper in keepersNotAssigned)
                    {
                        keepers.Add(session.QueryOver<TblKEEP_ID>().Where(x => x.KEEP_ID == Convert.ToInt32(keeper)).SingleOrDefault());
                    }
                    ViewBag.keepers = keepers;
                    ViewBag.idExhibit = idExhibit;
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Assign(int idExhibit, List<int> keepers)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    foreach (int id in keepers)
                    {
                        var assignment = new TblEXHIB_KEEP();

                        assignment.KEEP_ID = id;
                        assignment.EXHIB_ID = idExhibit;
                        assignment.ADD_DATE = System.DateTime.Now;
                        assignment.ACT_DT = assignment.ADD_DATE;

                        session.Save(assignment);
                    }
                    transaction.Commit();
                }
            }
            return Redirect("/KeeperAssignment/All");
        }

        public ActionResult All()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.assignments = session.QueryOver<TblEXHIB_KEEP>().List().OrderBy(x => x.REC_ID);
                }
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbAssignment = session.QueryOver<TblEXHIB_KEEP>().Where(x => x.REC_ID == id).SingleOrDefault();
                    session.Delete(dbAssignment);
                    transaction.Commit();
                }
            }
            return Redirect("/KeeperAssignment/All");
        }

    }
}

EthoTrak/Views/KeeperAssignment/All.cshtml
@using EthoTrak.DatabaseModels;

@section JavaScript
{
   <script type="text/javascript" src="@Url.Content("/Scripts/custom.js")"></script>
}

@{
    ViewBag.Title = "Enclosures Assignments";
}
<h3>Keeper Assignments :</h3>
<center>
    <span style="padding-right:20px;">
    @Html.ActionLink("Go back", "Management", "Home", null, new { @class="btn"})
    </span>
    @Html.ActionLink("Add a new assignment", "PickExhibit", "KeeperAssignment", null, new { @class="btn"})
</center>
<table class="table table-hover">
    <tr>
        <th>ID</th>
        <th>Keeper</th>
        <th>Exhibit</th>
        <th>Added on</th>       
        <th></th>
    </tr>

    @foreach (TblEXHIB_KEEP assignment in @ViewBag.assignments) {

    <tr>
        <td>@assignment.REC_ID</td>
        <td>@assignment.KEEP_ID</td>
        <td>@assignment.EXHIB_ID</td>
        <td>@assignment.ADD_DATE.Value.ToShortDateString()</td>
        <td>@Html.ActionLink("Delete", "Delete", "KeeperAssignment", new { id = assignment.REC_ID }, new { @class="btn btn-small btn-danger", onclick = " return DeleteConfirm('assignment')" })</td>
    </tr>
    }
</table>

EthoTrak/Views/KeeperAssignment/PickExhibit.cshtml
@{
    ViewBag.Title = "Select Exhibit";
}

<h4>Pick an exhibit :</h4>

@using (Html.BeginForm("ShowKeepers","KeeperAssignment"))
{

    <fieldset>

        <div class="editor-label">
            Exhibit Name
        </div>
            <div class="editor-field">
                
            @Html.DropDownList("idExhibit", new SelectList(@ViewBag.exhibits, "Value", "Text"))
                  
        </div> 

        <center><input type="submit" class="btn" value="Select Exhibit" /></center>
    <br />

    </fieldset>
}

EthoTrak/Views/KeeperAssignment/ShowKeepers.cshtml
@model EthoTrak.DatabaseModels.TblKEEP_ID

@using EthoTrak.DatabaseModels;

@{
    ViewBag.Title = "Index";
}

<h4>Select keepers</h4>

@using (Html.BeginForm("Assign", "KeeperAssignment"))
{
    @Html.Hidden("idExhibit",(object)@ViewBag.idExhibit)
    <fieldset>

        <div class="editor-label">
            Keepers
        </div>
       
 @foreach (TblKEEP_ID keeper in ViewBag.keepers)
            {
                <div style="line-height:10px;">
                    <input style="vertical-align:-2px;" type="checkbox" name="keepers" value="@keeper.KEEP_ID"><span style="padding-left:10px;" />
                    @keeper.FIRST @keeper.LAST
                </div>
                <br />
            }
 
        <br />
        <center><input type="submit" class="btn btn-success" value="Assign keeper to exhibit" /></center>
        <br />
    </fieldset>
}