EthoTrak/Controllers/EnclosureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EthoTrak.DatabaseModels;

namespace EthoTrak.Controllers
{
    public class EnclosureController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public ActionResult Add()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var areas = session.QueryOver<TblAREA_ID>().List();

                    IEnumerable<SelectListItem> list = areas.Select(a => new SelectListItem
                    {
                        Value = a.AREA_ID.ToString(),
                        Text = a.AREA
                    });

                    ViewBag.areas = list;
                }
            }

            var enclosure = new TblENCLOS_ID();
            return View(enclosure);
        }

        [HttpPost]
        public ActionResult Add(TblENCLOS_ID enclosure)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    enclosure.ACT_DT = System.DateTime.Now;

                    session.Save(enclosure);

                    transaction.Commit();
                }
            }

            return Redirect("/Enclosure/All");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var enclosure = session.QueryOver<TblENCLOS_ID>().Where(x => x.ENCLOS_ID == id).SingleOrDefault();

                    if (enclosure == null)
                    {
                        return HttpNotFound();
                    }

                    var areas = session.QueryOver<TblAREA_ID>().List();

                    IEnumerable<SelectListItem> list = areas.Select(a => new SelectListItem
                    {
                        Value = a.AREA_ID.ToString(),
                        Text = a.AREA
                    });

                    ViewBag.areas = list;

                    return View(enclosure);
                }
            }
        }

        [HttpPost]
        public ActionResult Edit(int id, TblENCLOS_ID enclosure)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbEnclosure = session.QueryOver<TblENCLOS_ID>().Where(x => x.ENCLOS_ID == id).SingleOrDefault();

                    dbEnclosure.ENCLOS = enclosure.ENCLOS;
                    dbEnclosure.AREA_ID = enclosure.AREA_ID;
                    dbEnclosure.COMMENTS = enclosure.COMMENTS;
                    dbEnclosure.ACT_DT = System.DateTime.Now;

                    session.Save(dbEnclosure);

                    transaction.Commit();
                }
            }
            return Redirect("/Enclosure/All");
        }

        public ActionResult All()
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    ViewBag.enclosures = session.QueryOver<TblENCLOS_ID>().List().OrderBy(x => x.ENCLOS_ID);
                }
            }

            return View();
        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.OpenSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var dbLocations = session.QueryOver<TblLOC_ID>().Where(x => x.ENCLOS_ID == id).List();

                    foreach (var location in dbLocations)
                    {
                        EthoTrak.Controllers.LocationController lc = new LocationController();
                        lc.Delete(location.LOC_ID);
                    }

                    var dbEnclosure = session.QueryOver<TblENCLOS_ID>().Where(x => x.ENCLOS_ID == id).SingleOrDefault();
                    session.Delete(dbEnclosure);
                    transaction.Commit();
                }
            }
            return Redirect("/Enclosure/All");
        }
    }
}

EthoTrak/Views/Enclosure/Add.cshtml
@model EthoTrak.DatabaseModels.TblENCLOS_ID
@{
    ViewBag.Title = "Enclosures - Add";
}

<br />
<center>@Html.ActionLink("Go back", "All", "Enclosure", null, new { @class="btn"})</center>
<br />

@using (Html.BeginForm())
{
    <fieldset>
        
        <legend>Add an Enclosure</legend>
        
        <div class="editor-label">
            Enclosure Name
        </div>
            <div class="editor-field">
            @Html.TextBoxFor(model => model.ENCLOS)
        </div>  
        
        <div class="editor-label">
            Area Name
        </div>
            <div class="editor-field">
            @Html.DropDownListFor(model => model.AREA_ID, new SelectList(@ViewBag.areas, "Value", "Text"))
        </div>  

        <div class="editor-label">
            Comments
        </div>
            <div class="editor-field">
            @Html.TextAreaFor(model => model.COMMENTS, new { style = "height:100px;" } )
        </div> 

        <br />
        <center><input type="submit" class="btn btn-success" value="Create Enclosure" /></center>
        <br />

    </fieldset>
}

EthoTrak/Views/Enclosure/All.cshtml
@using EthoTrak.DatabaseModels

@section JavaScript
{
   <script type="text/javascript" src="@Url.Content("/Scripts/custom.js")"></script>
}

@{
    ViewBag.Title = "Enclosures";
}
<h3>Enclosures :</h3>
<center>
    <span style="padding-right:20px;">
    @Html.ActionLink("Go back", "Management", "Home", null, new { @class="btn"})
    </span>
    @Html.ActionLink("Add an enclosure", "Add", "Enclosure", null, new { @class="btn"})
</center>
<table class="table table-hover">
    <tr>
        <th>#</th>
        <th>Enclosure Name</th>
        <th>Area Name</th>
        <th>Comments</th>
        <th>Last Modified</th>
        <th></th>
        <th></th>
    </tr>

    @foreach (TblENCLOS_ID enclosure in @ViewBag.enclosures) {

    <tr>
        <td>@enclosure.ENCLOS_ID</td>
        <td>@enclosure.ENCLOS</td>
        <td>@enclosure.AREA_ID</td>
        <td>@enclosure.COMMENTS</td>
        <td>@enclosure.ACT_DT</td> 
        <td>@Html.ActionLink("Edit", "Edit", "Enclosure", new {id = enclosure.ENCLOS_ID}, new { @class="btn btn-small"})</td>
        <td>@Html.ActionLink("Delete", "Delete", "Enclosure", new { id = enclosure.ENCLOS_ID }, new { @class="btn btn-small btn-danger", onclick = " return DeleteConfirm('enclosure')" })</td>
    </tr>
    }
</table>

EthoTrak/Views/Enclosure/Edit.cshtml
@model EthoTrak.DatabaseModels.TblENCLOS_ID

@{
    ViewBag.Title = "Enclosures - Edit";
}

<br />
<center>@Html.ActionLink("Go back", "All", "Enclosure", null, new { @class="btn"})</center>
<br />

@using (Html.BeginForm())
{
    <fieldset>
        
        <div class="editor-label">
            Enclosure Name
        </div>
            <div class="editor-field">
            @Html.TextBoxFor(model => model.ENCLOS)
        </div>  
        
        <div class="editor-label">
            Area Name
        </div>
            <div class="editor-field">
            @Html.DropDownListFor(model => model.AREA_ID, new SelectList(@ViewBag.areas, "Value", "Text"))
        </div> 

        <div class="editor-label">
            Comments
        </div>
            <div class="editor-field">
            @Html.TextAreaFor(model => model.COMMENTS, new { style = "height:100px;" } )
        </div> 
        

         <br />
        <center><input type="submit" class="btn btn-success" value="Save Changes" /></center>
        <br />

    </fieldset>
}

EthoTrak/Views/Enclosure/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Enclosures</h2>

@Html.ActionLink("Add an Enclosure", "Add", "Enclosure")
<br />
@Html.ActionLink("List all Enclosures", "All", "Enclosure")